version: '3'
services:
    app:
        image: muninn/caddy-microservice:app
        ports:
            - 12345:12345
        deploy:
            replicas: 3
    gateway:
        image: muninn/caddy-microservice:gateway
        ports:
            - 2015:2015
        depends_on:
            - app
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
